window.CATALOG = {
  studio: {
    name: "Software Society",
    tagline: "Un catálogo vivo de los juegos que vamos haciendo.",
    github: "https://github.com/DonMAriando",
    logo: "brand/software-society.png",
  },
  games: [
    {
      id: "corona-de-ceniza",
      title: "Corona de Ceniza",
      subtitle: "Crown of Ashes",
      blurb: "Gobernás Valdoria a través de generaciones. Cada decisión deja una cicatriz; cada muerte, una herencia.",
      status: "jugable",
      year: 2026,
      tags: ["estrategia", "narrativa"],
      cover: "covers/corona-de-ceniza.jpg",
      accent: "#c6a45b",
      play: "https://donmariando.github.io/Crown-of-Ashes/",
      repo: "https://github.com/DonMAriando/Crown-of-Ashes",
      featured: true,
    },
    {
      id: "flip-run",
      title: "FLIP//RUN",
      subtitle: "One touch / zero brakes",
      blurb: "Runner de precisión de un solo toque. Invertís la gravedad, rozás los orbes, no frenás.",
      status: "jugable",
      year: 2026,
      tags: ["arcade", "precisión"],
      cover: "covers/flip-run.svg",
      accent: "#3ec6ff",
      play: "https://donmariando.github.io/Flip_Run/",
      repo: "https://github.com/DonMAriando/Flip_Run",
    },
    {
      id: "no-ground-below",
      title: "No Ground Below",
      subtitle: "Demo 0.2 — física foddian",
      blurb: "Estás atrapado dentro de una campana de hierro. Un ancla, una cadena. Subir es opcional. Caer es inevitable.",
      status: "demo",
      year: 2026,
      tags: ["física", "escalada"],
      cover: "covers/no-ground-below.svg",
      accent: "#c5ccd3",
      play: "https://donmariando.github.io/No-Ground-Below/",
      repo: "https://github.com/DonMAriando/No-Ground-Below",
    },
    {
      id: "semilla-maldita",
      title: "Semilla Maldita",
      subtitle: "Roguelike por semilla",
      blurb: "Bajás, elegís reliquias, morís y compartís la semilla. La misma mazmorra para todo el mundo.",
      status: "jugable",
      year: 2026,
      tags: ["roguelike", "mazmorra"],
      cover: "covers/semilla-maldita.svg",
      accent: "#7cff6b",
      play: "https://donmariando.github.io/SemillaMaldita/",
      repo: "https://github.com/DonMAriando/SemillaMaldita",
    },
    {
      id: "smack",
      title: "SMACK!",
      subtitle: "Reacción vertical",
      blurb: "Pegale a lo peligroso, no toques lo tierno. Pensado para el celular: 45 segundos, combos y la Abuela Chancla.",
      status: "jugable",
      year: 2026,
      tags: ["arcade", "reacción"],
      cover: "covers/smack.svg",
      accent: "#ffd54a",
      play: "https://donmariando.github.io/Smack/",
      repo: "https://github.com/DonMAriando/Smack",
    },
  ],
};
